---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bgd1
  name: bgd1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgd1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bgd1
    spec:
      containers:
      - image: quay.io/redhatworkshops/bgd1:latest
        name: bgd1
        env:
        - name: COLOR
          value: "green"
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: v1
      volumes:
      - name: v1
        persistentVolumeClaim:
         claimName: demo
---
