apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo
  namespace: nfiiargo
  annotations:
   volume.beta.kubernetes.io/storage-class: demo-sc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
