apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo
  namespace: bgd1
  annotations:
   volume.beta.kubernetes.io/storage-class: dynamic-nfs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
