  
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: bgd
  name: bgd
  namespace: bgd1
spec:
  host: "bgd.apps.ocp-qa.nfii.com"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: bgd1
    weight: 100
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted
