  
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: nfiitest
  name: nfiitest
  namespace: nfiitest
spec:
  host: "nfiitest.apps.ocp-dev.nfii.com"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nfiitest
    weight: 100
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted
