---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nfiitest
  name: nfiitest
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nfiitest
---
